Application\CrmBundle\Entity\Project:
    exclusion_policy: ALL
    exclude: false
    read_only: false
    access_type: public_method # defaults to property
    virtual_properties:
        numberOfChildren:
            serialized_name: numberOfChildren
            type: integer
    properties:
        id:
            expose: true

        name:
            expose: true

        children:
            expose: true

#        client:
#            expose: true