<?php

namespace Application\QuotationGeneratorBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Application\QuotationGeneratorBundle\Entity\QuestionOption;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class QuestionOptionFixture extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(QuestionOptionFixture::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new QuestionOptionFixture();
        $item1->setText("a");
        $item1->setValue("a");
        $item1->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion1'));
        $item1->setCreatedAt(new \DateTime("2017-08-27 21:44:09"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption1', $item1);
        $manager->persist($item1);

        $item2 = new QuestionOptionFixture();
        $item2->setText("b");
        $item2->setValue("b");
        $item2->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion1'));
        $item2->setCreatedAt(new \DateTime("2017-08-27 21:44:41"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption2', $item2);
        $manager->persist($item2);

        $item3 = new QuestionOptionFixture();
        $item3->setText("template based");
        $item3->setValue("template based");
        $item3->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion2'));
        $item3->setCreatedAt(new \DateTime("2017-08-29 00:06:53"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption3', $item3);
        $manager->persist($item3);

        $item4 = new QuestionOptionFixture();
        $item4->setText("unique design");
        $item4->setValue("unique design");
        $item4->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion2'));
        $item4->setCreatedAt(new \DateTime("2017-08-29 00:07:06"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption4', $item4);
        $manager->persist($item4);

        $item5 = new QuestionOptionFixture();
        $item5->setText("basic");
        $item5->setValue("basic");
        $item5->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion3'));
        $item5->setCreatedAt(new \DateTime("2017-08-29 08:13:47"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption5', $item5);
        $manager->persist($item5);

        $item6 = new QuestionOptionFixture();
        $item6->setText("mailchimp");
        $item6->setValue("mailchimp");
        $item6->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion3'));
        $item6->setCreatedAt(new \DateTime("2017-08-29 08:13:55"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption6', $item6);
        $manager->persist($item6);

        $item7 = new QuestionOptionFixture();
        $item7->setText("sendy");
        $item7->setValue("sendy");
        $item7->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion3'));
        $item7->setCreatedAt(new \DateTime("2017-08-29 08:13:58"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption7', $item7);
        $manager->persist($item7);

        $item8 = new QuestionOptionFixture();
        $item8->setText("basic");
        $item8->setValue("basic");
        $item8->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion4'));
        $item8->setCreatedAt(new \DateTime("2017-08-29 08:17:37"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption8', $item8);
        $manager->persist($item8);

        $item9 = new QuestionOptionFixture();
        $item9->setText("advanced");
        $item9->setValue("advanced");
        $item9->setQuestion($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestion4'));
        $item9->setCreatedAt(new \DateTime("2017-08-29 08:17:43"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestionOption9', $item9);
        $manager->persist($item9);

    
        $manager->flush();
    }

}
