<?php

namespace Application\QuotationGeneratorBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Application\QuotationGeneratorBundle\Entity\Question;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class QuestionFixture extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(QuestionFixture::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new QuestionFixture();
        $item1->setText("template");
        $item1->setFormType("singlechoice");
        $item1->setGroup($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestionGroup2'));
        $item1->setAlias("template");
        $item1->setTags([
            $this->getReference('_reference_ApplicationClassificationBundleEntityTag1'),
        ]);
        $item1->setCreatedAt(new \DateTime("2017-08-27 21:43:51"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestion1', $item1);
        $manager->persist($item1);

        $item2 = new QuestionFixture();
        $item2->setText("Type of website");
        $item2->setFormType("singlechoice");
        $item2->setGroup($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestionGroup1'));
        $item2->setAlias("START");
        $item2->setCreatedAt(new \DateTime("2017-08-29 00:06:10"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestion2', $item2);
        $manager->persist($item2);

        $item3 = new QuestionFixture();
        $item3->setText("newsletter");
        $item3->setFormType("singlechoice");
        $item3->setGroup($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestionGroup3'));
        $item3->setAlias("newsletter");
        $item3->setTags([
            $this->getReference('_reference_ApplicationClassificationBundleEntityTag1'),
        ]);
        $item3->setCreatedAt(new \DateTime("2017-08-29 08:13:34"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestion3', $item3);
        $manager->persist($item3);

        $item4 = new QuestionFixture();
        $item4->setText("HR module");
        $item4->setFormType("singlechoice");
        $item4->setGroup($this->getReference('_reference_Proxies__CG__ApplicationQuotationGeneratorBundleEntityQuestionGroup3'));
        $item4->setAlias("hrmodule");
        $item4->setTags([
            $this->getReference('_reference_ApplicationClassificationBundleEntityTag1'),
        ]);
        $item4->setCreatedAt(new \DateTime("2017-08-29 08:17:26"));
        $this->addReference('_reference_ApplicationQuotationGeneratorBundleEntityQuestion4', $item4);
        $manager->persist($item4);

    
        $manager->flush();
    }

}
