<?php

namespace Application\ProjectAccountingBundle\Entity;

/**
 * SpentTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpentTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
