<?php

namespace Application\ProjectAccountingBundle\Entity;

/**
 * WorkScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
