<?php
namespace Application\AdminBundle\Block;

use Sonata\BlockBundle\Block\BaseBlockService;
use Sonata\BlockBundle\Block\BlockContextInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AdminSearchBlockService extends BaseBlockService
{
    /**
     * @param BlockContextInterface $blockContext
     * @param Response|null $response
     * @return Response
     */
    public function execute(BlockContextInterface $blockContext, Response $response = null)
    {
        if(false === $blockContext->getTemplate()) {
            $blockContext->setSetting('template', static::getTemplate());
        }
        return parent::execute($blockContext, $response); // TODO: Change the autogenerated stub
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultSettings(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'template'        => static::getTemplate()
        ));
    }

    /**
     * @return string
     */
    protected static function getTemplate() {
        return 'ApplicationAdminBundle:Block:dashboard_search_block.html.twig';
    }
}