imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extra/gedmo_doctrine_extensions.yml }
    - { resource: @OctetMessageBusBundle/Resources/config/config.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    sonata_user.google_authenticator.server: http://example.com
    jms_serializer.doctrine_proxy_subscriber.class: Application\CrmBundle\EventListener\DoctrineProxyHandler

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resource:
            - 'form_div_layout.html.twig'
            - 'ApplicationAdminBundle:Form:fields.html.twig'
            - 'CoreToolsBundle:Form:fields.html.twig'
            - 'CoreToolsBundle:Form:fields.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        mappings:
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree
                is_bundle: false

        auto_generate_proxy_classes: "%kernel.debug%"


        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Octet\Ticketing\Lib\Model\UserInterface: 'Application\UserBundle\Entity\User'
            Octet\Ticketing\Lib\Model\NoteRelatedInterface: 'Application\ObjectIdentityBundle\Entity\ObjectIdentity'
            Octet\Ticketing\Lib\Model\ReminderRelatedInterface: 'Application\ObjectIdentityBundle\Entity\ObjectIdentity'
            Core\ObjectIdentityBundle\Model\ObjectIdentityInterface: 'Application\ObjectIdentityBundle\Entity\ObjectIdentity'
        dql:
            string_functions:
                MATCH: Application\AdminBundle\DQL\MatchAgainstFunction


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_admin:
    security:
      handler: sonata.admin.security.handler.role
    title: %sonata_admin.title%
    options:
      title_mode: single_image
    title_logo: bundles/applicationadmin/img/logo_red.png
    templates:
      dashboard: SonataAdminBundle:Core:dashboard.html.twig
      user_block: ApplicationAdminBundle:Core:user_block.html.twig
      layout: SonataAdminBundle::app_standard_layout.html.twig
    assets:
      stylesheets:
        - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
        - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
        - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
        - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
        - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
        - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
        - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
        - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
        - bundles/sonatacore/vendor/select2/select2.css
        - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
        - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
        - bundles/sonataadmin/css/styles.css
        - bundles/sonataadmin/css/tree.css
        - bundles/sonataadmin/css/layout.css
        - bundles/applicationadmin/css/layout.css
        - bundles/applicationuser/css/layout.css
      javascripts:
        - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
        - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
        - bundles/sonatacore/vendor/moment/min/moment.min.js
        - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
        - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
        - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
        - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
        - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
        - bundles/sonataadmin/jquery/jquery.confirmExit.js
        - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
        - bundles/sonatacore/vendor/select2/select2.min.js
        - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
        - bundles/sonataadmin/vendor/iCheck/icheck.min.js
        - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
        - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
        - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
        - bundles/sonataadmin/Admin.js
        - bundles/sonataadmin/treeview.js
    dashboard:
      blocks:
        - { position: top, type: application_crm.block.dashboard_clients, class: 'col-md-12' }
        - { position: top, type: application_admin.block.dashboard.search, class: 'col-md-12' }


sonata_block:
    default_contexts: [cms]

    exception:
        default:
            filter:                 ignore_block_exception
            renderer:               throw
        filters:
            debug_only:             sonata.block.exception.filter.debug_only
            ignore_block_exception: sonata.block.exception.filter.ignore_block_exception
            keep_all:               sonata.block.exception.filter.keep_all
            keep_none:              sonata.block.exception.filter.keep_none
        renderers:
            inline:                 sonata.block.exception.renderer.inline
            inline_debug:           sonata.block.exception.renderer.inline_debug
            throw:                  sonata.block.exception.renderer.throw

    http_cache:
        handler: sonata.block.cache.handler.default
        listener: true

    templates:

    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        application_admin.block.dashboard.search:
            contexts:   [admin]

        sonata.admin.block.search_result:
            contexts:   [admin]

        application_crm.block.dashboard_clients:
            contexts:   [admin]

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)


#        sonata.admin_doctrine_orm.block.audit:
#            contexts:   [admin]

        sonata.page.block.container:
#            cache: core.cache.symfony

sonata_classification:
  class:
    category: Application\ClassificationBundle\Entity\Category
    context: Application\ClassificationBundle\Entity\ClassificationContext

sonata_media:
    # if you don't use default namespace configuration
    class:
        media: Application\MediaBundle\Entity\Media
        gallery: Application\MediaBundle\Entity\Gallery
        gallery_has_media: Application\MediaBundle\Entity\GalleryHasMedia
        category: Application\ClassificationBundle\Entity\Category
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true

sonata_block:
    blocks:
        #...
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

# app/config/security.yml
security:
    # [...]
    acl:
        connection: default


fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\UserBundle\Entity\User


    group:
        group_class:   Application\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)


sonata_user:
    security_acl:             true
    table:
        user_group:           user__user_group

    impersonating:
        route:                sonata_admin_dashboard
        parameters:           { path: / }

    google_authenticator:
        server:               %sonata_user.google_authenticator.server%
        enabled:              false

    manager_type:             orm
    class:
        user: Application\UserBundle\Entity\User
        group: Application\UserBundle\Entity\Group

    profile:
        form:
            type:                 sonata_user_profile
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_profile_form
            validation_groups:
                # Defaults:
                - Profile
                - Default


fos_rest:
    view:
        formats:
            json: true
            rss: true
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            Project:
                namespace_prefix: "Application\\CrmBundle\\Entity"
                path: "%kernel.root_dir%/Resources/serializer"