admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /

app_index:
    path: /
    defaults:
        _controller: ApplicationCrmBundle:Default:index

object_identity:
    resource: '@CoreObjectIdentityBundle/Resources/config/routing.yml'
    prefix: /


ticketing_notes_helper:
    resource: @OctetTicketingBundle/Resources/config/routing_note.yml
    prefix: /ticketing/notes/

