# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN]

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SONATA_ADMIN]


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Application\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin/*
            http_basic: ~


        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html


    access_control:
          # require ROLE_ADMIN for /admin*
#            - { path: ^/admin, roles: ROLE_ADMIN }