# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: admin
#                        roles: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN]
        fos_userbundle:
            id: fos_user.user_provider.username


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Application\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      /(.*)
            context:        frontend
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   sonata_user_admin_security_login
                username_parameter: _username
            logout:
                path:           /logout
            anonymous:    ~
            remember_me:
                key: remember_me_frontend
                lifetime: 31536000
                path: /
                domain: ~


    access_control:
          # require ROLE_ADMIN for /admin*
        - { path: ^/admin/, role: [ROLE_ADMIN] }