<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\UserBundle\Entity;

use Application\CrmBundle\Entity\Person;
use Application\CrmBundle\Entity\ProjectMembership;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer
     */
    protected $redmineUserId;

    /**
     * @var Collection|ProjectMembership[]
     */
    protected $projectMemberships;

    public function __construct()
    {
        $this->projectMemberships = new ArrayCollection();
        $this->enabled = true;
    }


    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function addProjectMembership(ProjectMembership $projectMembership)
    {
        $this->projectMemberships->add($projectMembership);
    }

    public function removeProjectMembership(ProjectMembership $projectMembership)
    {
        $this->projectMemberships->remove($projectMembership);
    }

    /**
     * @return \Application\CrmBundle\Entity\ProjectMembership[]|Collection
     */
    public function getProjectMemberships()
    {
        return $this->projectMemberships;
    }

    /**
     * Returns a string representation
     *
     * @return string
     */
    public function __toString()
    {
        return $this->getFirstname() || $this->getLastname()
            ? $this->getFirstname() . ' ' . $this->getLastname()
            : $this->getUsername();
    }


}