Application\QuotationGeneratorBundle\Entity\QuestionAction:
    type: entity
    table: null
    repositoryClass: Application\QuotationGeneratorBundle\Entity\ActionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        criteria:
            type: string
            length: 255
        actionType:
            type: integer
        actionParams:
            type: json_array
        position:
            type: integer
            nullable: true
        quotationItemName:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
        deletedAt:
            nullable: true
            type: datetime

    embedded:
        quotationItemPrice:
            class: Application\ProjectAccountingBundle\Entity\Price

    manyToOne:
        question:
            targetEntity: Application\QuotationGeneratorBundle\Entity\Question
            inversedBy: actions
        questionOption:
            targetEntity: Application\QuotationGeneratorBundle\Entity\QuestionOption
            inversedBy: actions
    manyToMany:
        implyQuestionsBySelection:
            targetEntity: Application\QuotationGeneratorBundle\Entity\Question
        implyQuestionsByTags:
            targetEntity: Application\ClassificationBundle\Entity\Tag
        implyQuestionsByGroups:
            targetEntity: Application\QuotationGeneratorBundle\Entity\QuestionGroup


    lifecycleCallbacks: {  }
