Application\QuotationGeneratorBundle\Entity\QuestionGroup:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        class:
            type: string
            lenght: 64
            nullable: true
    lifecycleCallbacks: {  }
