application_redmine_integration_gantt:
    path:     /gantt
    defaults:
        _controller: ApplicationRedmineIntegrationBundle:Gantt:index
        _sonata_admin: application_crm.admin.project


application_redmine_integration_fix_gantt:
    path:     /fix-gantt
    defaults:
        _controller: ApplicationRedmineIntegrationBundle:Project:ganttFixer
        _sonata_admin: application_crm.admin.project
