parameters:
    application_redmine_integration.redmine_api_url: 'http://redmine.assist01.gbart.h3.hu'

services:
    application_redmine_integration.menu.menu_build_listener:
        class: Application\RedmineIntegrationBundle\Menu\MenuBuildListener
        calls:
          - [setContainer, [@service_container]]
        tags:
          - { name: kernel.event_listener, event: menu.build.sonata_admin_sidebar, method: buildSonataAdminMenu  }

    application_redmine_integration.helper.ticket_time:
        class: Application\RedmineIntegrationBundle\Helper\TicketTimeHelper

    application_redmine_integration.helper.communication:
        class: Application\RedmineIntegrationBundle\Helper\CommunicationHelper
        calls:
          - [setRedmineDomain, ['%application_redmine_integration.redmine_api_url%']]
          - [setBrowser, ['@application_redmine_integration.http.client']]

    application_redmine_integration.http.listener.logger:
        class: Buzz\Listener\LoggerListener
        arguments: [['@logger', 'debug'], '[redmine] ']

    application_redmine_integration.http.client:
        class: Buzz\Browser
        calls:
          - ['setListener', ['@application_redmine_integration.http.listener.logger']]