<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\MediaBundle\Entity;

use Gedmo\Sortable\Sortable;
use Sonata\MediaBundle\Entity\BaseGalleryHasMedia as BaseGalleryHasMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class GalleryHasMedia extends BaseGalleryHasMedia implements Sortable
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string
     */
    protected $fileCategory;

    /**
     * GalleryHasMedia constructor.
     */
    public function __construct()
    {
        $this->position = 0;
        $this->enabled = true;

        parent::__construct();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getFileCategory()
    {
        if($this->getMedia()) {
            /** @var Media $media */
            $media = $this->getMedia();
            return $media->getFileCategory();
        }
        
        return '';
    }

    /**
     * @param mixed $fileCategory
     * @return $this
     */
    public function setFileCategory($fileCategory)
    {
        if($this->getMedia()) {
            /** @var Media $media */
            $media = $this->getMedia();
            $media->setFileCategory($fileCategory);
        }

        return $this;
    }

}