Application\ObjectIdentityBundle\Entity\ObjectIdentity:
    type: entity
    table: object_identity
    repositoryClass: Application\ObjectIdentityBundle\Entity\ObjectIdentityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        project:
            targetEntity: Application\CrmBundle\Entity\Project
        abstractClient:
            targetEntity: Application\CrmBundle\Entity\AbstractClient
        supplier:
            targetEntity: Application\CrmBundle\Entity\Supplier
        user:
            targetEntity: Application\UserBundle\Entity\User
            mappedBy: objectIdentity
        customProperty:
            targetEntity: Application\CrmBundle\Entity\CustomProperty
            mappedBy: objectIdentity
    oneToMany:
       indices:
           targetEntity: Core\ObjectIdentityBundle\Entity\ObjectIdentityIndex
           mappedBy:     objectIdentity
           fetch:        EXTRA_LAZY