Application\ObjectIdentityBundle\Entity\ObjectIdentity:
    type: entity
    table: object_identity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        project:
            targetEntity: Application\CrmBundle\Entity\Project
        abstractClient:
            targetEntity: Application\CrmBundle\Entity\AbstractClient
    manyToMany:
        notes:
            targetEntity: Octet\Ticketing\Bundle\Entity\Note
        reminders:
            targetEntity: Octet\Ticketing\Bundle\Entity\Reminder