Application\UserBundle\Entity\User:
    table: user__user
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        redmineUserId:
            column: redmine_user_id
            type: integer
            nullable: true
    manyToOne:
        primaryGroup:
            targetEntity: Application\UserBundle\Entity\Group
    oneToMany:
        projectMemberships:
            targetEntity: Application\CrmBundle\Entity\ProjectMembership
            mappedBy: user