Application\CrmBundle\Entity\AbstractClient:
    type: entity
    table: crm__client
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
        loggable:
          logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry

    inheritanceType: single_table
    discriminatorColumn:
        name: type
        type: string

    fields:
        financialInformation:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
        referral:
            type: string
            length: 255
            nullable: true
    manyToOne:
        fileset:
            targetEntity: Application\MediaBundle\Entity\Gallery
            cascade: [all]
    manyToMany:
        groups:
            targetEntity: Application\UserBundle\Entity\Group
    oneToMany:
        contacts:
            targetEntity: Application\CrmBundle\Entity\Contact
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned
        projects:
            targetEntity: Application\CrmBundle\Entity\Project
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned
        addresses:
            targetEntity: Application\CrmBundle\Entity\Address
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned
    lifecycleCallbacks:
        prePersist: [updateFilesetName]
        preUpdate: [updateFilesetName]
