Application\CrmBundle\Entity\Address:
    type: entity
    table: crm__address
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: '2'
            nullable: true
        state:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        postalCode:
            type: string
            length: 16
            nullable: true
        street:
            type: string
            length: 255
            nullable: true
        streetNumber:
            type: string
            length: 255
            nullable: true
        postbox:
            type: string
            length: 32
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        type:
            type: string
            length: 16
            nullable: true
    manyToOne:
        client:
            targetEntity: Application\CrmBundle\Entity\Client
            inversedBy: addresses
    lifecycleCallbacks: {  }
