Application\CrmBundle\Entity\Client:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: json_array
            nullable: false
        phone:
            type: datetime
        createdAt:
            type datetime
    lifecycleCallbacks: {  }