Application\CrmBundle\Entity\Client:
    type: entity
    table: crm__client
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
        loggable:
          logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry
    fields:
        type:
            type: string
            length: '16'
            nullable: true
            gedmo:
                - versioned
        financialInformation:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        status:
            type: string
            length: '16'
            nullable: true
            gedmo:
                - versioned
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
        referral:
            type: string
            length: 255
            nullable: true
    embedded:
        company:
            class: Application\CrmBundle\Entity\Company
            gedmo:
                - versioned

    manyToOne:
        owner:
            targetEntity: Application\UserBundle\Entity\User
            gedmo:
                - versioned
        projectManager:
            targetEntity: Application\UserBundle\Entity\User
            gedmo:
                - versioned
    oneToMany:
        projects:
            targetEntity: Application\CrmBundle\Entity\Project
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned
    manyToMany:
        contacts:
            targetEntity: Application\CrmBundle\Entity\Contact
            cascade: [all]
            gedmo:
                - versioned
    lifecycleCallbacks: {  }
