Application\CrmBundle\Entity\Client:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '16'
            nullable: true
        financialInformation:
            type: string
            length: 255
            nullable: true
        status:
            type: string
            length: '16'
            nullable: true
        createdAt:
            type: datetime
    manyToOne:
        company:
            targetEntity: Application\CrmBundle\Entity\Company
            cascade: [all]
        account:
            targetEntity: Application\CrmBundle\Entity\Person
    oneToMany:
        projects:
            targetEntity: Application\CrmBundle\Entity\Project
            mappedBy: client
            cascade: [all]
    manyToMany:
        contactPersons:
            targetEntity: Application\CrmBundle\Entity\Person
            cascade: [all]
    lifecycleCallbacks: {  }
