Application\CrmBundle\Entity\Company:
    type: embeddable

    fields:
        name:
            type: string
            length: 255
            nullable: true
            type: string
            length: 255
            nullable: true
        sectorOfActivity:
            type: string
            length: 255
            nullable: true
            type: string
            length: 8
            nullable: true
        country:
            type: string
            length: 8
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        phone1:
            type: string
            length: 255
            nullable: true
        phone2:
            type: string
            length: 255
            nullable: true
        fax:
            type: string
            length: 255
            nullable: true
