Application\CrmBundle\Entity\Company:
    type: embeddable
    gedmo:
        loggable:
            logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry


    fields:
        name:
            type: string
            length: 255
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        sectorOfActivity:
            type: string
            length: 255
            nullable: true
            type: string
            length: 8
            nullable: true
            gedmo:
                - versioned
        country:
            type: string
            length: 8
            nullable: true
            gedmo:
                - versioned
        website:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        email:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        phone1:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        phone2:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        fax:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
