Application\CrmBundle\Entity\Company:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        name:
            type: string
            length: 255
            nullable: true
            type: string
            length: 255
            nullable: true
        sectorOfActivity:
            type: string
            length: 255
            nullable: true
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        mainContactInformation:
            targetEntity: Application\CrmBundle\Entity\ContactInformation
            cascade: [all]
    oneToMany:
        memberships:
            targetEntity: Application\CrmBundle\Entity\CompanyMembership
            mappedBy: company
            cascade: [all]
            orphanRemoval: true
        leads:
            targetEntity: Application\CrmBundle\Entity\Lead
            cascade: [all]
            orphanRemoval: true
            mappedBy: company
    manyToMany:
        websites:
            targetEntity: Application\CrmBundle\Entity\Website
            cascade: [all]
            orphanRemoval: true

    lifecycleCallbacks: {  }
