Application\CrmBundle\Entity\CompanyMembership:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: 255
            nullable: true
        startDate:
            type: date
            nullable: true
        endDate:
            type: date
            nullable: true
        workPermit:
            type: string
            length: 255
            nullable: true
        holidaysRemaining:
            type: string
            length: 255
            nullable: true
    manyToOne:
        company:
            targetEntity: Application\CrmBundle\Entity\Company
            inversedBy: memberships
        person:
            targetEntity: Application\CrmBundle\Entity\Person
            inversedBy: companyMemberships
            cascade: [persist]
    lifecycleCallbacks: {  }
