Application\CrmBundle\Entity\Company:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
            type: string
            length: 255
            nullable: true
        sectorOfActivity:
            type: string
            length: 255
            nullable: true
    manyToOne:
        mainContactInformation:
            targetEntity: Application\CrmBundle\Entity\ContactInformation
            cascade: [all]
    oneToMany:
        memberships:
            targetEntity: Application\CrmBundle\Entity\CompanyMembership
            mappedBy: company
            cascade: [all]
            orphanRemoval: true
        offices:
            targetEntity: Application\CrmBundle\Entity\Office
            mappedBy: company
            cascade: [all]
            orphanRemoval: true
    manyToMany:
        websites:
            targetEntity: Application\CrmBundle\Entity\Website
            cascade: [all]
            orphanRemoval: true

    lifecycleCallbacks: {  }
