Application\CrmBundle\Entity\ContactInformation:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        companyPhone:
            type: string
            length: '64'
        privatePhone:
            type: string
            length: '64'
        companyEmail:
            type: string
            length: '128'
        privateEmail:
            type: string
            length: '128'
        skypeId:
            type: string
            length: '64'
        facebookId:
            type: string
            length: '64'
    lifecycleCallbacks: {  }
