Application\CrmBundle\Entity\ContactInformation:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        companyPhone:
            type: string
            length: '64'
            nullable: true
        privatePhone:
            type: string
            length: '64'
            nullable: true
        companyEmail:
            type: string
            length: '128'
            nullable: true
        privateEmail:
            type: string
            length: '128'
            nullable: true
        skypeId:
            type: string
            length: '64'
            nullable: true
        facebookId:
            type: string
            length: '64'
            nullable: true
    lifecycleCallbacks: {  }
