Application\CrmBundle\Entity\Office:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
    manyToOne:
        company:
            targetEntity: Application\CrmBundle\Entity\Company
            inversedBy: offices
        address:
            targetEntity: Application\CrmBundle\Entity\Address
            cascade: [persist]
    lifecycleCallbacks: {  }
