Application\CrmBundle\Entity\Person:
    type: embeddable
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        dateOfBirth:
            type: datetime
            nullable: true
        gender:
            type: string
            length: '2'
            nullable: true
        nationality:
            type: string
            length: '2'
            nullable: true
        directLinePhone:
            type: string
            length: '64'
            nullable: true
        companyPhone:
            type: string
            length: '64'
            nullable: true
        privatePhone:
            type: string
            length: '64'
            nullable: true
        companyEmail:
            type: string
            length: '128'
            nullable: true
        privateEmail:
            type: string
            length: '128'
            nullable: true
        skypeId:
            type: string
            length: '64'
            nullable: true
        facebookId:
            type: string
            length: '64'
            nullable: true
        twitter:
            type: string
            length: '64'
            nullable: true
        instagram:
            type: string
            length: '64'
            nullable: true

    lifecycleCallbacks: {  }
