Application\CrmBundle\Entity\Person:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        personalData:
            targetEntity: Application\CrmBundle\Entity\PersonalData
            cascade: [all]
        contactInformation:
            targetEntity: Application\CrmBundle\Entity\ContactInformation
            cascade: [all]
    oneToOne:
        user:
            targetEntity: Application\UserBundle\Entity\User
            mappedBy: person
            cascade: [persist]
    oneToMany:
        companyMemberships:
            targetEntity: Application\CrmBundle\Entity\CompanyMembership
            mappedBy: person
            cascade: [all]
        projectMemberships:
            targetEntity: Application\CrmBundle\Entity\ProjectMembership
            mappedBy: person
            cascade: [all]
    lifecycleCallbacks: {  }
