Application\CrmBundle\Entity\Person:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        personalData:
            targetEntity: Application\CrmBundle\Entity\PersonalData
            cascade: [all]
        contactInformation:
            targetEntity: Application\CrmBundle\Entity\ContactInformation
            cascade: [all]
        user:
            targetEntity: Application\UserBundle\Entity\User
            cascade: [persist]
    oneToMany:
        companyMemberships:
            targetEntity: Application\CrmBundle\Entity\CompanyMembership
            mappedBy: person
            cascade: [all]
        companyMemberships:
            targetEntity: Application\CrmBundle\Entity\ProjectMembership
            mappedBy: person
            cascade: [all]
    lifecycleCallbacks: {  }
