Application\CrmBundle\Entity\PersonalData:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        dateOfBirth:
            type: datetime
            nullable: true
        gender:
            type: string
            length: '2'
            nullable: true
        nationality:
            type: string
            length: '2'
            nullable: true
    manyToOne:
        avatar:
            targetEntity: Application\MediaBundle\Entity\Media
    lifecycleCallbacks: {  }
