Application\CrmBundle\Entity\ProjectMembership:
    type: entity
    table: crm__project_membership
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: 255
        createdAt:
            type: datetime
    manyToOne:
        project:
            targetEntity: Application\CrmBundle\Entity\Project
            inversedBy: memberships
        user:
            targetEntity: Application\UserBundle\Entity\User
            inversedBy: projectMemberships
    lifecycleCallbacks: {  }
