Application\CrmBundle\Entity\Project:
    type: entity
    table: crm__project
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        loggable:
            logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        name:
            type: string
            length: 255
            gedmo:
                - versioned
        description:
            type: text
            nullable: true
            gedmo:
                - versioned
        status:
            type: string
            length: '16'
            gedmo:
                - versioned
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        client:
            targetEntity: Application\CrmBundle\Entity\Client
            inversedBy: projects
            gedmo:
                - versioned
        fileset:
            targetEntity: Application\MediaBundle\Entity\Gallery
            cascade: [all]
        objectIdentity:
            targetEntity: Application\ObjectIdentityBundle\Entity\ObjectIdentity
    manyToMany:
        groups:
            targetEntity: Application\UserBundle\Entity\Group
    oneToMany:
        memberships:
            targetEntity: Application\CrmBundle\Entity\ProjectMembership
            mappedBy: project
            cascade: [all]
            orphanRemoval: true
            gedmo:
                - versioned
    lifecycleCallbacks:
        prePersist: [updateFilesetName]
        preUpdate: [updateFilesetName]
