Application\CrmBundle\Entity\Project:
    type: entity
    table: crm__project
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        status:
            type: string
            length: '16'
        createdAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        client:
            targetEntity: Application\CrmBundle\Entity\Client
            inversedBy: projects
    oneToMany:
        memberships:
            targetEntity: Application\CrmBundle\Entity\ProjectMembership
            mappedBy: project
            cascade: [all]
            orphanRemoval: true
    lifecycleCallbacks: {  }
