Application\CrmBundle\Entity\Project:
    type: entity
    table: crm__project
    repositoryClass: Application\CrmBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
    gedmo:
        tree:
            type: nested

        loggable:
            logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry

        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        name:
            type: string
            length: 255
            gedmo:
                - versioned

        description:
            type: text
            nullable: true
            gedmo:
                - versioned

        status:
            type: string
            length: '16'
            gedmo:
                - versioned

        createdAt:
            type: datetime

        updatedAt:
            type: datetime
            nullable: true

        deletedAt:
            type: datetime
            nullable: true

        lft:
            type: integer
            gedmo:
              - treeLeft
        rgt:
            type: integer
            gedmo:
              - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
              - treeRoot
        lvl:
            type: integer
            gedmo:
              - treeLevel

    manyToOne:
        parent:
            targetEntity: Application\CrmBundle\Entity\Project
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent

        client:
            targetEntity: Application\CrmBundle\Entity\Client
            inversedBy: projects
            gedmo:
                - versioned
        fileset:
            targetEntity: Application\MediaBundle\Entity\Gallery
            cascade: [all]

        objectIdentity:
            targetEntity: Application\ObjectIdentityBundle\Entity\ObjectIdentity
            cascade: [all]

    manyToMany:
        groups:
            targetEntity: Application\UserBundle\Entity\Group

    oneToMany:
       children:
           targetEntity: Application\CrmBundle\Entity\Project
           mappedBy: parent
           fetch: EXTRA_LAZY
           orderBy:
              lft: ASC

       memberships:
            targetEntity: Application\CrmBundle\Entity\ProjectMembership
            mappedBy: project
            cascade: [all]
            orphanRemoval: true
            gedmo:
                - versioned
    lifecycleCallbacks:
        prePersist: [updateFilesetName]
        preUpdate: [updateFilesetName]
