Application\CrmBundle\Entity\Supplier:
    type: entity
    gedmo:
        loggable:
            logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry
    embedded:
        company:
            class: Application\CrmBundle\Entity\Company
            gedmo:
                - versioned

    manyToOne:
        owner:
            targetEntity: Application\UserBundle\Entity\User
            gedmo:
                - versioned
        projectManager:
            targetEntity: Application\UserBundle\Entity\User
            gedmo:
                - versioned
