Application\CrmBundle\Entity\Supplier:
    type: entity
    gedmo:
        loggable:
            logEntryClass: Core\LoggableEntityBundle\Entity\LogEntry
    embedded:
        company:
            class: Application\CrmBundle\Entity\Company
            gedmo:
                - versioned

    manyToOne:
        owner:
            targetEntity: Application\UserBundle\Entity\User
            gedmo:
                - versioned
        ownerGroup:
            targetEntity: Application\UserBundle\Entity\Group
        projectManager:
            targetEntity: Application\UserBundle\Entity\User
            gedmo:
                - versioned
    oneToMany:
        projects:
            targetEntity: Application\CrmBundle\Entity\Project
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned
        contacts:
            targetEntity: Application\CrmBundle\Entity\Contact
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned
        addresses:
            targetEntity: Application\CrmBundle\Entity\Address
            mappedBy: client
            cascade: [all]
            gedmo:
                - versioned