services:
    sonata.admin.client:
        class: Application\CrmBundle\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Manage", label: "Clients" }
        arguments:
            - ~
            - Application\CrmBundle\Entity\Client
            - ~
            - @doctrine.orm.default_entity_manager
        calls:
            - [ setTranslationDomain, [AppicationCrmBundle]]

    sonata.admin.project:
        class: Application\CrmBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Manage", label: "Projects" }
        arguments:
            - ~
            - Application\CrmBundle\Entity\Project
            - ~
            - @doctrine.orm.default_entity_manager
        calls:
            - [ setTranslationDomain, [AppicationCrmBundle]]

    sonata.admin.project.manager:
        class: Application\CrmBundle\Admin\ProjectManagerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Manage", label: "Project Managers" }
        arguments:
            - ~
            - Application\CrmBundle\Entity\ProjectManager
            - ~
            - @doctrine.orm.default_entity_manager
        calls:
            - [ setTranslationDomain, [AppicationCrmBundle]]