services:
    application_crm.admin.contact:
        class: Application\CrmBundle\Admin\ContactAdmin
        arguments: [~, Application\CrmBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Persons, label: Contact Persons}

    application_crm.admin.address:
        class: Application\CrmBundle\Admin\AddressAdmin
        arguments: [~, Application\CrmBundle\Entity\Address, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: Address, show_in_dashboard: false }

    application_crm.admin.client:
        class: Application\CrmBundle\Admin\ClientAdmin
        arguments: [~, Application\CrmBundle\Entity\Client, ApplicationCrmBundle:ClientAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: application_crm.admin.client }

    application_crm.admin.supplier:
        class: Application\CrmBundle\Admin\SupplierAdmin
        arguments: [~, Application\CrmBundle\Entity\Supplier, ApplicationCrmBundle:ClientAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: application_crm.admin.supplier }

    application_crm.admin.project:
        class: Application\CrmBundle\Admin\ProjectAdmin
        arguments: [~, Application\CrmBundle\Entity\Project, ApplicationCrmBundle:ProjectAdmin]
        calls:
            - [addChild, ['@application_quotation_generator.admin.fill_out']]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Projects, label: All projects }

    application_crm.admin.project_membership:
        class: Application\CrmBundle\Admin\ProjectMembershipAdmin
        arguments: [~, Application\CrmBundle\Entity\ProjectMembership, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: ProjectMembership, show_in_dashboard: false }

    application_crm.event_listener.menu.admin:
        class: Application\CrmBundle\Menu\AdminMenuBuildListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: onAdminMenuBuild }

    application_crm.admin.extension.owner_group_manager:
        class: Application\CrmBundle\Admin\Extension\OwnerGroupManagerExtension
        arguments:
            - @application_crm.security.helper
        tags:
            - { name: sonata.admin.extension, global: true }

    application_crm.security.helper:
        class: Application\CrmBundle\Security\CrmSecurityHelper
        arguments:
            - @security.token_storage
            - @security.authorization_checker

    application_crm.eventy_listener.owner_group_setter:
        class: Application\CrmBundle\EventListener\OwnerGroupSetterListener
        lazy: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    application_crm.twig.extension:
        class: Application\CrmBundle\Twig\CrmBundleExtension
        tags:
            - { name: twig.extension }

    application_crm.model_builder.client_index:
        class: Application\CrmBundle\ModelBuilder\ClientIndexBuilder
        tags:
            - { name: model_builder, class: 'Application\CrmBundle\Entity\Client' }

    application_crm.model_builder.project_index:
        class: Application\CrmBundle\ModelBuilder\ProjectIndexBuilder
        tags:
            - { name: model_builder, class: 'Application\CrmBundle\Entity\Project' }

    application_crm.mailer:
        class: Application\CrmBundle\Mailer\CrmMailer
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: command_handler, handles: octet_ticketing_send_reminder_notification, method: handleSendReminderNotificationCommand }

    application_crm.admin.sector_of_activity:
        class: Application\CrmBundle\Admin\SectorOfActivityAdmin
        arguments: [~, Application\CrmBundle\Entity\SectorOfActivity, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: System, label: 'Sector Of Activity' }

    application_crm.util.search.client_result_provider:
        class: Application\CrmBundle\Util\Search\ClientResultProvider
        arguments:
            - @sonata.admin.pool
        tags:
            - { name: admin.result_provider, class: 'Application\CrmBundle\Entity\Client' }

    application_crm.event.listener.admin_post_update:
        class: Application\CrmBundle\EventListener\PostUpdateEventListener
        arguments:
          - '@core_object_identity.manager'
        tags:
          - {name: doctrine.event_listener, event: postUpdate, method: postUpdate}
          - {name: doctrine.event_listener, event: postPersist, method: postPersist}

    application_crm.block.file_categories:
        class: Application\CrmBundle\Block\FileCategoryBlockService
        arguments:
            - 'application_crm.block.file_categories'
            - '@templating'
            - '@doctrine.orm.entity_manager'
            - '@sonata.admin.pool'
        tags:
            - { name: sonata.block }

    application_crm.block.dashboard_clients:
        class: Application\CrmBundle\Block\ClientsBlockService
        arguments:
            - 'application_crm.block.dashboard_clients'
            - '@templating'
            - '@doctrine.orm.entity_manager'
            - '@sonata.admin.pool'
        tags:
            - { name: sonata.block }

    application_crm.event_listener.crm_block_event_listener:
        class: Application\CrmBundle\EventListener\CrmBlockEventListener
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.render_file_categories, method: onRenderFileCategories }

