services:

    application_crm.admin.contact:
        class: Application\CrmBundle\Admin\ContactAdmin
        arguments: [~, Application\CrmBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Contact Persons, show_in_dashboard: false }
#

    application_crm.admin.address:
        class: Application\CrmBundle\Admin\AddressAdmin
        arguments: [~, Application\CrmBundle\Entity\Address, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: Address, show_in_dashboard: false }

    application_crm.admin.client:
        class: Application\CrmBundle\Admin\ClientAdmin
        arguments: [~, Application\CrmBundle\Entity\Client, ApplicationCrmBundle:ClientAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Clients }

    application_crm.admin.supplier:
        class: Application\CrmBundle\Admin\SupplierAdmin
        arguments: [~, Application\CrmBundle\Entity\Supplier, ApplicationCrmBundle:ClientAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Suppliers }

    application_crm.admin.project:
        class: Application\CrmBundle\Admin\ProjectAdmin
        arguments: [~, Application\CrmBundle\Entity\Project, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Projects, label: All projects }

    application_crm.admin.project_membership:
        class: Application\CrmBundle\Admin\ProjectMembershipAdmin
        arguments: [~, Application\CrmBundle\Entity\ProjectMembership, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: ProjectMembership, show_in_dashboard: false }

    application_crm.event_listener.menu.admin:
        class: Application\CrmBundle\Menu\AdminMenuBuildListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_listener, event: menu.build.sonata_admin_sidebar, method: onAdminMenuBuild }

    application_crm.admin.extension.owner_group_manager:
        class: Application\CrmBundle\Admin\Extension\OwnerGroupManagerExtension
        calls:
            - [setTokenStorage, [@security.token_storage]]
            - [setAuthorizationChecker, [@security.authorization_checker]]
        tags:
            - { name: sonata.admin.extension, global: true }

    application_crm.twig.extension:
        class: Application\CrmBundle\Twig\CrmBundleExtension
        tags:
            - { name: twig.extension }
