services:
    application_crm.admin.personal_data:
        class: Application\CrmBundle\Admin\PersonalDataAdmin
        arguments: [~, Application\CrmBundle\Entity\PersonalData, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: PersonalData  }

#    application_crm.admin.person:
#        class: Application\CrmBundle\Admin\PersonAdmin
#        arguments: [~, Application\CrmBundle\Entity\Person, SonataAdminBundle:CRUD]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: People  }

    application_crm.admin.contact_information:
        class: Application\CrmBundle\Admin\ContactInformationAdmin
        arguments: [~, Application\CrmBundle\Entity\ContactInformation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: ContactInformation, show_in_dashboard: false }

    application_crm.admin.team_member:
        class: Application\CrmBundle\Admin\TeamMemberAdmin
        arguments: [~, Application\CrmBundle\Entity\TeamMember, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Team, icon: group  }

    application_crm.admin.contact_person:
        class: Application\CrmBundle\Admin\ContactPersonAdmin
        arguments: [~, Application\CrmBundle\Entity\ContactPerson, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Contact Persons }


    application_crm.admin.individual:
        class: Application\CrmBundle\Admin\IndividualAdmin
        arguments: [~, Application\CrmBundle\Entity\Individual, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Individuals  }


    application_crm.admin.address:
        class: Application\CrmBundle\Admin\AddressAdmin
        arguments: [~, Application\CrmBundle\Entity\Address, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: Address, show_in_dashboard: false }

    application_crm.admin.company:
        class: Application\CrmBundle\Admin\CompanyAdmin
        arguments: [~, Application\CrmBundle\Entity\Company, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contact Manager, label: Companies,  show_in_dashboard: true }

    application_crm.admin.company_membership:
        class: Application\CrmBundle\Admin\CompanyMembershipAdmin
        arguments: [~, Application\CrmBundle\Entity\CompanyMembership, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: CompanyMembership, show_in_dashboard: false }

    application_crm.admin.lead:
        class: Application\CrmBundle\Admin\LeadAdmin
        arguments: [~, Application\CrmBundle\Entity\Lead, ApplicationCrmBundle:LeadAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Leads, label: All leads }

    application_crm.admin.project:
        class: Application\CrmBundle\Admin\ProjectAdmin
        arguments: [~, Application\CrmBundle\Entity\Project, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Projects, label: All projects }

    application_crm.admin.project_membership:
        class: Application\CrmBundle\Admin\ProjectMembershipAdmin
        arguments: [~, Application\CrmBundle\Entity\ProjectMembership, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: system_tables, label: ProjectMembership, show_in_dashboard: false }

    application_crm.event_listener.menu.admin:
        class: Application\CrmBundle\Menu\AdminMenuBuildListener
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_listener, event: menu.build.sonata_admin_sidebar, method: onAdminMenuBuild }